### ISSUE TITLE
Signup down?  

### ISSUE THREAD

**Issue by causten** [onnx/sigs#131]
I attended the ONNX Community Day  sessions and they were interesting.  I tried to sign up but I get this error message.  

Going to https://slack.lfai.foundation/ hits this issue with Chrome...

Error: error:0308010C:digital envelope routines::unsupported
   at new Hash (node:internal/crypto/hash:71:19)
   at Object.createHash (node:crypto:133:10)
   at weakhash (/usr/local/lib/node_modules/slackin/node_modules/etag/index.js:168:6)
   at etag (/usr/local/lib/node_modules/slackin/node_modules/etag/index.js:59:7)
   at wetag (/usr/local/lib/node_modules/slackin/node_modules/express/lib/utils.js:46:10)
   at ServerResponse.send (/usr/local/lib/node_modules/slackin/node_modules/express/lib/response.js:169:14)
   at /usr/local/lib/node_modules/slackin/dist/index.js:128:9
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/slackin/node_modules/express/lib/router/layer.js:82:5)
   at next (/usr/local/lib/node_modules/slackin/node_modules/express/lib/router/route.js:110:13)
   at Route.dispatch (/usr/local/lib/node_modules/slackin/node_modules/express/lib/router/route.js:91:3)

**Comment by jcwchen** [comment]
Hi @causten,
Please use this link instead: https://join.slack.com/t/lfaifoundation/shared_invite/zt-o65errpw-gMTbwNr7FnNbVXNVFkmyNA.

XREF: https://github.com/onnx/onnx/issues/4058#issuecomment-1060694336.
